baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Seven的个人网站'

hasCJKLanguage = true

[outputs]
home = ["HTML"]

[Params]
  # enableToTop = false
  [Params.hero]
    img = "/images/1-2.jpg"
    slogan = "ONE THING I KNOW, THAT IS I KNOW NOTHING"

  # LOGO
  [Params.logo]
  #  img = '/images/logo-bookmark.svg'
  #  img_footer = '/images/logo-bookmark-footer.svg'
  #  str = 'text'

  # Copyright 
  [Params.copyright]
    owner = 'Seven'
    start_year = '2022'

  # Article Meta
  [Params.articleMeta]
  #  enableAuthor = false
  #  disableDate = false
  #  disableModifiedDate = false
  #  disableCountWords = false
  #  disableReadTime = false
  #  disableHero = false
  #  disableToc = false

#[markup]
#  [markup.tableOfContents]
#    endLevel = 3
#    startLevel = 2

[frontmatter]
  lastmod = ['lastmod', ':fileModTime', ':default']

[menu]
  [[menu.main]]
    name = "Posts"
    pre = "pen-tool"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "Categories"
    pre = "categories"
    url = "/categories/"
    weight = 2
  [[menu.main]]
    name = "tags"
    pre = "tags"
    url = "/tags/"
    weight = 3

[module]
  [module.hugoVersion]
    extended = false
    min      = "0.112.0"
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "hugo_stats.json"
    target = "assets/watching/hugo_stats.json"

[build]
  writeStats = true
  [[build.cachebusters]]
    source = "assets/watching/hugo_stats\\.json"
    target = "styles\\.css"
  [[build.cachebusters]]
    source = "(postcss|tailwind)\\.config\\.js"
    target = "css"
  [[build.cachebusters]]
    source = "assets/.*\\.(js|ts|jsx|tsx)"
    target = "js"
  [[build.cachebusters]]
    source = "assets/.*\\.(.*)$"
    target = "$1"
