[build.environment]
  HUGO_VERSION = "0.124.0"

[build]
  publish = "exampleSite/public"
  command = "hugo --gc -s exampleSite --minify"

[context.deploy-preview]
  command = "hugo -s exampleSite --minify -D -F -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo -s exampleSite --minify --gc -b $DEPLOY_PRIME_URL"