languageCode = "en"
languageName = "English"
title = "Byte-Sized Posts"
weight = 2

[params]
  description = "A Simple And Beautiful Blog Theme For Hugo"
  omitCategoryOnMenu = true
  categoryName = "Category"
